### PR TITLE
ColdFusion compatibility fixes

### PR DESCRIPTION
**Pull request by jimblesphere**
Changes made to allow application to run under ColdFusion versions 2016 and 2021. Also modified file browser code to enable selecting images in editor and performing file manipulations that failed in ColdFusion.

### CODE REVIEW

**Comment by guustnieuwenhuis** [comment]
Thanks for your contribution @jimblesphere!
We're fixing a few other issues as well and will include your work in the upcoming patch version. We'll merge the PR once the branch for that version is ready.

**Comment by guustnieuwenhuis** [comment]
Hi @jimblesphere,
We have a few requests for changes on your PR:

- could you merge the 7.3.1 branch into your branch, so that you have our latest changes
- could you remove the code that you've commented out? We like to keep our code as clean as possible and not leave any code in that has been commented out.
- The changes you've made to replace `&&`, `==`, `!=`, etc., these are working fine with Adobe ColdFusion. Could you revert them?
- could you rebuild the filebrowser.min.js file after these changes?

**Comment by jimblesphere** [comment]
Gus:

What version of ColdFusion did you test with? The changes made to replace
&&, ==, != are not necessary with ColdFusion 2021 but they are necessary to
function with ColdFusion 2016, which does not support these operators in
CFML tags like <cfif>. I don't have a CF 2018 installation to test with so
I don't know if those operators will work in that version. Also, semicolons
at the end of lines in cfscript are mandatory in CF 2016 and were made
optional in CF 2018.

jim

**Comment by guustnieuwenhuis** [comment]
The semi colons at the end of the line are no problem, that's a good style.
Thanks for pointing out the support for ACF 2016, let's keep your changes.

Once you've picked up the other requests, we can merge your contribution and release it. :)

**Review by guustnieuwenhuis — APPROVED** [review]

**Pull request merged**
